import { useState } from "react";
import { DoubtEntry, commonPhaseFears, ivfSteps } from "../data/site";
import { Send, Trash2, Lightbulb, Printer } from "lucide-react";

interface DoubtJournalProps {
  currentPhaseId: string | null;
  doubts: DoubtEntry[];
  onAddDoubt: (doubt: DoubtEntry) => void;
  onDeleteDoubt: (id: string) => void;
}

export default function DoubtJournal({ currentPhaseId, doubts, onAddDoubt, onDeleteDoubt }: DoubtJournalProps) {
  const [text, setText] = useState("");
  const [showFears, setShowFears] = useState(false);

  const phaseId = currentPhaseId || "initial-consultation";
  const phaseFears = commonPhaseFears[phaseId] || commonPhaseFears["initial-consultation"];
  const currentPhaseTitle = ivfSteps.find((s) => s.id === phaseId)?.title || "This phase";

  const handleSubmit = () => {
    if (!text.trim()) return;
    const timestamp = new Date().toISOString();
    const entry: DoubtEntry = {
      id: `${phaseId}-${timestamp}-${text.trim().slice(0, 12)}`,
      text: text.trim(),
      timestamp,
      phaseId,
      answered: false,
    };
    onAddDoubt(entry);
    setText("");
  };

  const handleQuickAdd = (fear: string) => {
    const timestamp = new Date().toISOString();
    const entry: DoubtEntry = {
      id: `${phaseId}-${timestamp}-${fear.slice(0, 12)}`,
      text: fear,
      timestamp,
      phaseId,
      answered: false,
    };
    onAddDoubt(entry);
  };

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (win) {
      win.document.write(`
        <html><head><title>My Questions for the Doctor</title>
        <style>body{font-family:sans-serif;padding:40px;line-height:1.6} h1{color:#1e40af} .entry{margin-bottom:16px;border-left:3px solid #3b82f6;padding-left:12px} .date{color:#6b7280;font-size:13px}</style>
        </head><body>
        <h1>Questions for My Doctor</h1>
        <p style="color:#6b7280">Prepared on ${new Date().toLocaleDateString()}</p>
        <hr style="margin:24px 0" />
        ${doubts.map((d) => `<div class="entry"><div class="date">${new Date(d.timestamp).toLocaleDateString()} at ${new Date(d.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><p>${d.text}</p></div>`).join("")}
        <hr style="margin:24px 0" />
        <p style="color:#9ca3af;font-size:13px">Generated by IVF Companion — share this with your doctor at your next appointment.</p>
        </body></html>
      `);
      win.document.close();
      win.print();
    }
  };

  // Group doubts by date
  const groupedDoubts: Record<string, DoubtEntry[]> = {};
  doubts.forEach((d) => {
    const dateKey = new Date(d.timestamp).toLocaleDateString();
    if (!groupedDoubts[dateKey]) groupedDoubts[dateKey] = [];
    groupedDoubts[dateKey].push(d);
  });

  return (
    <div className="w-full rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-white">Doubt & Question Journal</h3>
          <p className="text-xs text-slate-400">Write down your questions and confusions as they come</p>
        </div>
        {doubts.length > 0 && (
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 rounded-xl bg-white/5 px-3 py-1.5 text-[11px] text-slate-300 hover:bg-white/10 transition"
          >
            <Printer className="h-3.5 w-3.5" />
            Print for Doctor
          </button>
        )}
      </div>

      {/* Input area */}
      <div className="mb-3">
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder={`What's on your mind about ${currentPhaseTitle}?`}
          className="w-full resize-none rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white placeholder-slate-500 outline-none transition focus:border-blue-400/40 focus:ring-1 focus:ring-blue-400/20"
          rows={3}
        />
        <div className="mt-2 flex items-center justify-between">
          <button
            onClick={() => setShowFears(!showFears)}
            className="flex items-center gap-1.5 text-[11px] text-slate-400 hover:text-slate-300 transition"
          >
            <Lightbulb className="h-3.5 w-3.5" />
            Common concerns about {currentPhaseTitle}
          </button>
          <button
            onClick={handleSubmit}
            disabled={!text.trim()}
            className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-blue-500 to-cyan-400 px-4 py-1.5 text-xs font-medium text-white disabled:opacity-40 transition hover:shadow-lg hover:shadow-blue-500/20"
          >
            <Send className="h-3.5 w-3.5" />
            Save
          </button>
        </div>
      </div>

      {/* Quick-add common fears */}
      {showFears && (
        <div className="mb-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3">
          <p className="mb-2 text-[11px] font-medium text-amber-300">Common concerns at this stage — tap to add:</p>
          <div className="flex flex-wrap gap-1.5">
            {phaseFears.map((fear, i) => (
              <button
                key={i}
                onClick={() => handleQuickAdd(fear)}
                className="rounded-full border border-amber-500/20 bg-amber-500/10 px-2.5 py-1 text-[10px] text-amber-200 transition hover:bg-amber-500/20"
              >
                + {fear.length > 40 ? fear.slice(0, 40) + "..." : fear}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Saved entries */}
      {doubts.length > 0 && (
        <div className="space-y-3 max-h-60 overflow-y-auto">
          {Object.entries(groupedDoubts).map(([date, entries]) => (
            <div key={date}>
              <p className="mb-1.5 text-[10px] font-medium text-slate-500 uppercase tracking-wider">{date}</p>
              <div className="space-y-1.5">
                {entries.map((entry) => (
                  <div
                    key={entry.id}
                    className="group flex items-start gap-2 rounded-xl bg-white/[0.03] p-2.5 border border-white/5"
                  >
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-500/10 text-[10px] text-blue-300">
                      !
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs leading-relaxed text-slate-200">{entry.text}</p>
                      <p className="mt-0.5 text-[10px] text-slate-500">
                        {new Date(entry.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                      </p>
                    </div>
                    <button
                      onClick={() => onDeleteDoubt(entry.id)}
                      className="shrink-0 opacity-0 group-hover:opacity-100 transition p-1 rounded hover:bg-red-500/10"
                    >
                      <Trash2 className="h-3 w-3 text-red-400" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {doubts.length === 0 && (
        <p className="py-3 text-center text-xs text-slate-500">
          No questions yet. Write down anything that's on your mind — you can print them for your next doctor's visit.
        </p>
      )}
    </div>
  );
}
