import { ivfSteps } from "../data/site";
import { Printer, FileText, CheckSquare, AlertTriangle, Heart } from "lucide-react";

interface PhaseSummarySheetProps {
  currentPhaseId: string | null;
}

export default function PhaseSummarySheet({ currentPhaseId }: PhaseSummarySheetProps) {
  const phase = ivfSteps.find((s) => s.id === currentPhaseId) || ivfSteps[0];

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head>
        <title>Phase Summary: ${phase.title}</title>
        <style>
          body{font-family:system-ui,sans-serif;padding:40px;line-height:1.6;color:#1f2937;max-width:700px;margin:0 auto}
          h1{font-size:24px;color:#1e40af;margin-bottom:4px}
          .sub{color:#6b7280;font-size:14px;margin-bottom:24px}
          h2{font-size:18px;color:#1e40af;margin-top:28px;border-bottom:1px solid #e5e7eb;padding-bottom:6px}
          ul{padding-left:20px}
          li{margin-bottom:6px}
          .tip{background:#fef3c7;border-left:4px solid #f59e0b;padding:12px 16px;margin:16px 0;border-radius:8px}
          .warning{background:#fee2e2;border-left:4px solid #ef4444;padding:12px 16px;margin:16px 0;border-radius:8px}
          .selfcare{background:#ecfdf5;border-left:4px solid #10b981;padding:12px 16px;margin:16px 0;border-radius:8px}
          .footer{margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af}
          @media print{body{padding:20px} .no-print{display:none}}
        </style>
      </head><body>
        <h1>${phase.title}</h1>
        <p class="sub">${phase.subtitle} &bull; Duration: ${phase.duration}</p>
        <p>${phase.summary}</p>

        <h2>Key Instructions</h2>
        <ul>${phase.details.map((d) => `<li>${d}</li>`).join("")}</ul>

        <h2>Questions to Ask Your Provider</h2>
        <ul>${phase.questionsToAsk.map((q) => `<li>${q}</li>`).join("")}</ul>

        <div class="warning">
          <strong>⚠️ Warning Signs to Watch For</strong>
          <ul style="margin-top:8px">
            <li>Severe abdominal pain or bloating that doesn't improve</li>
            <li>Heavy bleeding (more than a period)</li>
            <li>Fever above 100.4°F (38°C)</li>
            <li>Difficulty breathing or chest pain</li>
            <li>Severe headache or vision changes</li>
          </ul>
        </div>

        <div class="tip">
          <strong>💡 Provider's Advice</strong>
          <p style="margin-top:4px">${phase.specialistVoice}</p>
        </div>

        <div class="selfcare">
          <strong>🧘 Self-Care Checklist</strong>
          <ul style="margin-top:8px">
            <li>☐ Get adequate rest — your body is working hard</li>
            <li>☐ Stay hydrated — drink at least 8 glasses of water</li>
            <li>☐ Eat nourishing meals with protein and vegetables</li>
            <li>☐ Take a gentle walk if you feel up to it</li>
            <li>☐ Practice the breathing exercise for this phase</li>
            <li>☐ Talk to your partner about how you're feeling</li>
            <li>☐ Write down any new questions for your doctor</li>
          </ul>
        </div>

        <div class="footer">
          <p>Generated by IVF Companion on ${new Date().toLocaleDateString()}</p>
          <p>This is an educational summary. Always follow your clinic's specific instructions.</p>
        </div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="w-full rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-emerald-400" />
          <h3 className="text-sm font-semibold text-white">Phase Summary Sheet</h3>
        </div>
        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-400 px-3.5 py-2 text-[11px] font-medium text-white transition hover:shadow-lg hover:shadow-emerald-500/20"
        >
          <Printer className="h-3.5 w-3.5" />
          Print / Save PDF
        </button>
      </div>

      <p className="text-xs text-slate-400">
        One-click printable summary for <span className="text-slate-200 font-medium">{phase.title}</span> — includes key instructions, questions for your doctor, warning signs, and a self-care checklist. Share it with your provider to save consultation time.
      </p>

      <div className="mt-3 grid grid-cols-2 gap-2">
        <div className="flex items-start gap-2 rounded-xl bg-blue-500/5 border border-blue-400/10 p-2.5">
          <CheckSquare className="h-3.5 w-3.5 text-blue-400 mt-0.5" />
          <div>
            <p className="text-[11px] font-medium text-blue-200">Key Instructions</p>
            <p className="text-[10px] text-slate-400">{phase.details.length} steps</p>
          </div>
        </div>
        <div className="flex items-start gap-2 rounded-xl bg-amber-500/5 border border-amber-400/10 p-2.5">
          <AlertTriangle className="h-3.5 w-3.5 text-amber-400 mt-0.5" />
          <div>
            <p className="text-[11px] font-medium text-amber-200">Warning Signs</p>
            <p className="text-[10px] text-slate-400">What to watch for</p>
          </div>
        </div>
        <div className="flex items-start gap-2 rounded-xl bg-emerald-500/5 border border-emerald-400/10 p-2.5">
          <Heart className="h-3.5 w-3.5 text-emerald-400 mt-0.5" />
          <div>
            <p className="text-[11px] font-medium text-emerald-200">Self-Care</p>
            <p className="text-[10px] text-slate-400">7-item checklist</p>
          </div>
        </div>
        <div className="flex items-start gap-2 rounded-xl bg-purple-500/5 border border-purple-400/10 p-2.5">
          <FileText className="h-3.5 w-3.5 text-purple-400 mt-0.5" />
          <div>
            <p className="text-[11px] font-medium text-purple-200">Questions</p>
            <p className="text-[10px] text-slate-400">{phase.questionsToAsk.length} for your doctor</p>
          </div>
        </div>
      </div>
    </div>
  );
}
